### ISSUE TITLE
Make The feature to copy the code..

### ISSUE THREAD

**Issue by Nipunkhattri** [Nipunkhattri/Quotes-generator#1]
Make a button of copy and on clicking on it we can copy the text of quotes

**Comment by Nevish-302** [comment]
can you assign this to me?

**Comment by Nipunkhattri** [comment]
Assigned! Go ahead @Nevish-302

**Comment by Candy505** [comment]
Hey ! m a bit confused. Do I need to be assigned before making a pull request ? I have already done a pull req. @Nipunkhattri
