### ISSUE TITLE
To direct the quote to twitter post page 

### ISSUE THREAD

**Issue by Nipunkhattri** [Nipunkhattri/Quotes-generator#2]
Add a feature to clicking on tweet button the quote written go on the twitter post page and we can post their..

**Comment by ManavMalhotra** [comment]
I can do this please assign this task to me

**Comment by amansingh1373** [comment]
@Nipunkhattri i want to add this feature kindly assign me this task

**Comment by ysh-01** [comment]
I would like to add this feature. Please assign this task to me.
