### ISSUE TITLE
Change bg on clicking new quote

### ISSUE THREAD

**Issue by rohitchoudhary09** [Nipunkhattri/Quotes-generator#20]
Let's change the image every time the buttons get clicked, it will improve the UI.

Assign this to me!

**Comment by rohitchoudhary09** [comment]
Hey!, actually I was working on that and it was assigned to me, But you merged that. Also, images take eternity to load now. So, is there any way I can still work on this? Sent from Mail for Windows From: Nipun khatriSent: 11 October 2022 22:29To: Nipunkhattri/Quotes-generatorCc: Rohit Choudhary; AssignSubject: Re: [Nipunkhattri/Quotes-generator] Change bg on clicking new quote (Issue #20) Closed #20 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by Nipunkhattri** [comment]
Okk i am opening the new issue you can push their ..
