### ISSUE TITLE
Improving Font Family & UI of Application

### ISSUE THREAD

**Issue by MohitNamdev22** [Nipunkhattri/Quotes-generator#7]
The current UI and font family looks very unprofessional, it can be made attractive. Can I work on this Issue under Hacktoberfest 2022?

![image](https://user-images.githubusercontent.com/89779447/193817933-174ed99a-00ca-44f3-a752-066a0bb1609e.png)

**Comment by amansingh1373** [comment]
@Nipunkhattri  i have done some changes kindly have a look at it i have resolved the two opened issues
![changes](https://user-images.githubusercontent.com/67228126/193877672-07516e77-39f9-47eb-b158-142bc1d83c25.png)
